version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  app:
    image: ghcr.io/shmookoff/shmoo.space:latest
    restart: on-failure
    environment:
      - MONGODB_URI
      - NEXT_PUBLIC_APP_URL
      - PAYLOAD_SECRET
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
volumes:
  mongodb_data:
